
INSERT INTO USERS(USER_NAME,USER_LOGIN,USER_EMAIL,USER_BIRTHDAY)
VALUES ('Nikita','qwerty','maifwrfwefwl@mail.ru','2022-02-03');
INSERT INTO USERS(USER_NAME,USER_LOGIN,USER_EMAIL,USER_BIRTHDAY)
VALUES ('eeeee','ew','fewfw@mail.ru','2022-02-03');
INSERT INTO FILMS(FILM_NAME, FILM_DESCRIPTION, FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA, FILM_RATE)
VALUES ('Джедай','кррутой джедай','2000-12-12',123,1,3);
INSERT INTO FILMS(FILM_NAME, FILM_DESCRIPTION, FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA, FILM_RATE)
VALUES ('fewf','ewf fewf','2000-12-12',123,1,3);
INSERT INTO FILMS(FILM_NAME, FILM_DESCRIPTION, FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA, FILM_RATE)
VALUES ('wefewf','ewfwefwefwe fewf','2000-12-12',123,1,3);
